### ISSUE TITLE
Testing error

### ISSUE THREAD

**Issue by adityac8** [HyeongseokSon1/KPAC#1]
Hi

Thank you for providing the code for your paper.

I am trying to replicate the results of the paper and would like to know which tensorflow version you use.
I have tried testing with tensorflow 1.10 and run into the following error with `python main_eval_3level.py`

```
[TL] UpSampling2dLayer sha_attention/0: is_scale:False size:[140.0, 210.0] method:1 align_corners:False
TypeError: Expected int32, got 140.0 of type 'float' instead
```

Thanks

**Comment by HyeongseokSon1** [comment]
I'm sorry for this late response.
As I have graduated from my school, I have no test PC now.

I guess that this problem can be solved by modifying the scale parameter in UpSampling2dLayer in model.py.
For example, please change [hrg/4,wrg/4] to [int(hrg/4),int(wrg/4)].
Please apply this modification to the other layers.

Thank you.

**Comment by adityac8** [comment]
Thanks a lot. Making the above changes, I was able to run the code.
