### ISSUE TITLE
the problem for evaluation result.

### ISSUE THREAD

**Issue by jucaizhai** [HyeongseokSon1/KPAC#3]
Thank you for your excellent work! When we used the pre training model provided by you to evaluate, we found that the effect was very poor. The index of PSNR was only 5. The main problem encountered is that there are many parallel color artifacts in the evaluated image.
We wondered whether it was the problem of the installation environment. The environment we have configured is as follows.
Or can you provide us with pictures for your evaluation？Thank you!
The environment of python and tf is based on the version you provide.

_tflow_select             2.1.0                     
absl-py                   0.15.0           
astor                     0.8.0                    
backports                 1.1               
backports.functools-lru-cache 1.6.4                 
backports.weakref         1.0.post1                
blas                      1.0                     
c-ares                    1.18.1               
ca-certificates           2022.07.19          
certifi                   2020.6.20         
cloudpickle               1.3.0                     
cudatoolkit               9.0                  
cudnn                     7.6.5                 
cupti                     9.0.176                      
cycler                    0.10.0                    
decorator                 4.4.2                     
easydict                  1.10                      
enum34                    1.1.6                    
funcsigs                  1.0.2                   
futures                   3.3.0                    
gast                      0.5.3              
grpcio                    1.27.2           
intel-openmp              2020.2                
kiwisolver                1.1.0                 
libffi                    3.3                  
libgcc-ng                 11.2.0               
libgfortran-ng            7.3.0               
libprotobuf               3.11.2            
libstdcxx-ng              11.2.0        
markdown                  3.1.1                   
matplotlib                2.2.5                     
mkl                       2020.2                  
mkl-service               2.3.0        
mkl_fft                   1.0.15           
mkl_random                1.1.0            
mock                      3.0.5                    
ncurses                   6.3              
networkx                  2.2                 
numpy                     1.16.6           
numpy-base                1.16.6           
opencv-python             4.0.0.21                 
openssl                   1.1.1q             
Pillow                    6.2.2                  
pip                       19.3.1                   
protobuf                  3.11.2           
pyparsing                 2.4.7                  
python                    2.7.12            
python-dateutil           2.8.2                
pytz                      2022.5                 
PyWavelets                1.0.3                 
readline                  8.1.2           
scikit-image              0.14.5            
scipy                     1.2.3                    
setuptools                44.0.0                   
six                       1.16.0             
sqlite                    3.39.3               
subprocess32              3.5.4                
tensorboard               1.10.0           
tensorflow                1.10.0          
tensorflow-base           1.10.0          
tensorflow-gpu            1.10.0              
termcolor                 1.1.0                    
tk                        8.6.12               
werkzeug                  1.0.1             
wheel                     0.37.1             
zlib                      1.2.12

**Comment by HyeongseokSon1** [comment]
Since I've graduated from my school, I cannot check the versions of other libraries now. I also guess this problem would be related to software versions. I wonder the effect of _tflow_select 2.1.0. Also, in my experience, the version of PIL image can affect the results due to different image sampling results.

**Comment by jucaizhai** [comment]
Thank you! I'll try the _tflow_select. Here's another question. The SSIM indicators in the paper are different from those in other relevant papers. For example, DPDNet's evaluation in its paper is 0.786, but it is shown here as 0.850，We also use the python library  **scikit-image** to calculate 0.786. Is it another version of SSIM? It seems that the second calculation method has not been found.

**Comment by HyeongseokSon1** [comment]
I used MATLAB for calculating both PSNR and SSIM. I think the parameters used for SSIM in MATLAB and Python libraries are different.

**Comment by jucaizhai** [comment]
Thank you!
